DROP DATABASE IF EXISTS DAJOCA;
CREATE TABLE DAJOCA;
USE DAJOCA;

CREATE TABLE TRABAJADOR(
IDTRABAJADOR INT,
NOMBRE VARCHAR(40),
DNI CHAR(8),
DIRECCION VARCHAR(30),
CONSTRAINT PK1 PRIMARY KEY (IDTRABAJADOR)
);

CREATE TABLE INVENTARIO(
IDINVENTARIO INT,
COD INT,
ESTANTERIA INT,
ALMACEN INT,
CONSTRAINT PK2 PRIMARY KEY (IDINVENTARIO)
);

CREATE TABLE SEDE(
IDSEDE INT,
DIRECCION VARCHAR(30),
ESPECIALIZACION VARCHAR(20),
CONSTRAINT PK3 PRIMARY KEY (IDSEDE)
);

CREATE TABLE CLIENTES(
IDCLIENTE INT,
DNI CHAR(8),
APELLIDOS VARCHAR(40),
NOMBRE VARCHAR(40),
CONSTRAINT PK4 PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PEDIDOS(
IDPEDIDO INT,
NOMBRE VARCHAR(40),
PRECIO DECIMAL(6,2),
CONSTRAINT PK5 PRIMARY KEY (IDPEDIDO)
);

CREATE TABLE PEDIDOSCLIENTES(
IDPEDIDOCLIENTE INT,
FECHAPEDIDO DATE,
IDPEDIDO INT,
IDCLIENTE INT,
CONSTRAINT PK6 PRIMARY KEY (IDPEDIDOCLIENTE),
CONSTRAINT FK1 FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO),
CONSTRAINT FK2 FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE VENTAS(
IDVENTAS INT,
NOMBRE VARCHAR(40),
PRECIO DECIMAL(6,2),
IDPEDIDO INT,
CONSTRAINT PK7 PRIMARY KEY (IDVENTAS),
CONSTRAINT FK3 FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDOO)
);

CREATE TABLE PROVEEDOR(
IDPROVEEDOR INT,
NOMBRE VARCHAR(40),
DNI CHAR(8),
IDPEDIDO INT,
CONSTRAINT PK8 PRIMARY KEY (IDPROVEEDOR),
CONSTRAINT FK4 FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO)
);

CREATE TABLE PROVEEDORSEDE(
IDPROVEEDORSEDE INT,
COD INT,
IDSEDE INT,
IDPROVEEDOR INT,
CONSTRAINT PK9 PRIMARY KEY (IDPROVEEDORSEDE),
CONSTRAINT FK5 FOREIGN KEY (IDSEDE) REFERENCES SEDE(IDSEDE),
CONSTRAINT FK6 FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR)
);

CREATE TABLE INVENTARIOSEDE(
IDINVENTARIOSEDE INT,
COD INT,
ESPECIALIZACION VARCHAR(20),
IDSEDE INT,
IDINVENTARIO INT,
CONSTRAINT PK10 PRIMARY KEY (IDINVENTARIOOSEDE),
CONSTRAINT FK7 FOREIGN KEY (IDSEDE) REFERENCES SEDE(IDSEDE),
CONSTRAINT FK8 FOREIGN KEY (IDINVENTARIO) REFERENCES INVENTARIO(IDINVENTARIO)
);

CREATE TABLE TRABAJADORINVENTARIO(
IDTRABAJADORINVENTARIO INT,
IDINVENTARIO INT,
IDTRABAJADOR INT,
CONSTRAINT PK11 PRIMARY KEY (IDTRABAJADORINVENTARIO),
CONSTRAINT FK9 FOREIGN KEY (IDINVENTARIO) REFERENCES INVENTARIO(IDINVENTARIO),
CONSTRAINT FK10 FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADOR(IDTRABAJADOR)

);
