DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE COCHE(
MATRICULA VARCHAR(7),
MARCA VARCHAR(15),
MODELO VARCHAR(15),
CONSTRAINT PK1 PRIMARY KEY (MATRICULA)
);

CREATE TABLE DEPARTAMENTO(
ID INT AUTO_INCREMENT,
NOMBRE VARCHAR(40),
UBICACION VARCHAR(30),
CONSTRAINT PK2 PRIMARY KEY (ID)
);

CREATE TABLE EMPLEADOS(
DNI_NIE CHAR(9),
NOMBRE VARCHAR(40),
APELLIDOS VARCHAR(40),
FECHANACIMIENTO DATE,
MATRICULA VARCHAR(7),
ID INT,
CONSTRAINT PK3 PRIMARY KEY (DNI_NIE),
CONSTRAINT FK1 FOREIGN KEY (MATRICULA) REFERENCES COCHE(MATRICULA),
CONSTRAINT FK2 FOREIGN KEY (ID) REFERENCES DEPARTAMENTO(ID)
);
INSERT INTO COCHE(MATRICULA, MARCA, MODELO) VALUES('XM785MJ', 'ALFA ROMEO', 'MITO');
INSERT INTO COCHE(MATRICULA, MARCA, MODELO) VALUES('9413JPL', 'SEAT', 'IBIZA'); 

INSERT INTO DEPARTAMENTO(NOMBRE, UBICACION) VALUES('HR', 'DEODE');

INSERT INTO EMPLEADOS(DNI_NIE, NOMBRE, APELLIDOS, FECHANACIMIENTO, MATRICULA) 
VALUES 
('X7919907H', 'JOAQUIN VALENTIN', 'OTTONELLO', '2005-08-09', '9413JPL'),
('A95337555', 'FERNANDO', 'PEREZ', '2004-12-06', 'XM785MJ'),
('Y23345896', 'DAVID', 'POOLIDULA', '2000-11-16', NULL),
('56789534Z', 'JORGE', 'GARCÍA', '2003-02-14', NULL);

UPDATE COCHE SET MARCA='SEAT', MODELO='IBIZA' WHERE MATRICULA='9413JPL';
UPDATE DEPARTAMENTO SET NOMBRE='IT' WHERE ID=1;

