DROP DATABASE IF EXISTS BANCO;
CREATE DATABASE BANCO;
USE BANCO;

CREATE TABLE PRODUCTOS(
EAN CHAR(13),
NOMBRE VARCHAR(40),
MARCA VARCHAR(20),
PRECIO DECIMAL(6,2),
CONSTRAINT PK1 PRIMARY KEY (EAN)
);

CREATE TABLE CUPONES(
IDCUPON INT,
FECHAVENCIMIENTO DATE,
PORCENTAJEDESCUENTO INT,
CONSTRAINT PK2 PRIMARY KEY (IDCUPON)
);

CREATE TABLE CLIENTES(
PASAPORTE CHAR(9),
NOMBRE VARCHAR(40),
DIRECCION VARCHAR(50),
CUENTABANCARIA CHAR(20),
IDCUPON INT,
CONSTRAINT PK3 PRIMARY KEY (PASAPORTE),
CONSTRAINT FK1 FOREIGN KEY (IDCUPON) REFERENCES CUPONES(IDCUPON)
);

CREATE TABLE PEDIDOS(
IDPEDIDO INT,
EAN CHAR(13),
CONSTRAINT PK4 PRIMARY KEY (IDPEDIDO),
CONSTRAINT FK2 FOREIGN KEY (EAN) REFERENCES PRODUCTOS(EAN) 
);

CREATE TABLE CLIENTESPEDIDOS(
IDCLIPED INT,
PASAPORTE CHAR(9),
IDPEDIDO INT,
CONSTRAINT PK5 PRIMARY KEY (IDCLIPED),
CONSTRAINT FK3 FOREIGN KEY (PASAPORTE) REFERENCES CLIENTES(PASAPORTE),
CONSTRAINT FK4 FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO)
);
