DROP DATABASE GIMNASIOS;
CREATE DATABASE GIMNASIOS;
USE GIMNASIOS;

CREATE TABLE MEMBERS(
ID DECIMAL(3,0),
NAME VARCHAR(40),
EMAIL VARCHAR(50),
PHONE_NUMBER DECIMAL(15,0),

CONSTRAINT PK PRIMARY KEY (ID)
);

CREATE TABLE INSTRUCTIONS(
ID DECIMAL(4,0),
NAME VARCHAR(20),

CONSTRAINT PK PRIMARY KEY (ID)
); 

CREATE TABLE TYPES(
ID DECIMAL(3,0),
TYPE_NAME VARCHAR(20),

CONSTRAINT PK PRIMARY KEY (ID)
);

CREATE TABLE CLASSES(
ID DECIMAL(4,0),
CLASS_NAME VARCHAR(30),
TYPE_ID DECIMAL(3,0),
DURATION INT,

CONSTRAINT PK PRIMARY KEY (ID),
CONSTRAINT FK1 FOREIGN KEY (TYPE_ID) REFERENCES TYPES (ID)
);

CREATE TABLE CLASS_SCHEDULE(
ID DECIMAL(3,0),
CLASS_ID DECIMAL(3,0),
INSTRUCTOR_ID DECIMAL(3,0),
START_TIME INT,
END_TIME INT,

CONSTRAINT PK PRIMARY KEY (ID),
CONSTRAINT FK2 FOREIGN KEY (CLASS_ID) REFERENCES CLASSES (ID),
CONSTRAINT FK3 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTIONS (ID)
);

CREATE TABLE MEMBER_SIGNUPS(
ID DECIMAL(4,0),
MEMBER_ID DECIMAL(4,0),
CLASS_SCHEDULE DECIMAL(4,0),
NO_SHOW BOOL,

CONSTRAINT PK PRIMARY KEY (ID),
CONSTRAINT FK4 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS (ID),
CONSTRAINT FK5 FOREIGN KEY (CLASS_SCHEDULE) REFERENCES CLASS_SCHEDULE (ID)
);

ALTER TABLE INSTRUCTIONS ADD SURNAME VARCHAR(40);
ALTER TABLE MEMBERS DROP COLUMN PHONE_NUMBER;





